marketplaces:
  amazon:
    batch_size: 10
    schedule_time: "*/5 * * * *"  # every 5 minutes
    retry_delay: 300  # 5 minutes in seconds
    max_retries: 3
    rate_limit: 1  # requests per second
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5"

  walmart:
    batch_size: 5
    schedule_time: "*/10 * * * *"  # every 10 minutes
    retry_delay: 600  # 10 minutes in seconds
    max_retries: 3
    rate_limit: 0.5  # requests per second
    headers:
      User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
      Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
      Accept-Language: "en-US,en;q=0.5" 